### ISSUE TITLE
No near 2cm at rest

### ISSUE THREAD

**Issue by mgrouch** [Infineon/RaspberryPi_DPS#2]
I'm trying to develop a system for measuring wave height.
Even when sensor is at rest it doesn't give near 2 cm accuracy.

Here is my code (it's based on this code)

https://github.com/bareboat-necessities/RaspberryPi_DPS/blob/master/Examples/TempPressValues_310.py

Thanks

**Comment by ederjc** [comment]
Dear @mgrouch,
I apologize for the delayed response and missing out your issue!
If this issue is still relevant, could you please re-open it? I'll gladly look into it and try to reproduce your problem then.
Best regards
Julian
